# Example configuration for the Intelligent Code Review Agent.
# Copy this file to `reviewer.toml` and customize it for your project.

# --- Paths Configuration ---
# Optional configuration for a pre-built vector index used for
# Retrieval-Augmented Generation.
[index]
path = ".reviewer/index/index.json"

[paths]
# Paths to include (allow) in the analysis. Globs are supported.
allow = ["src/**/*.rs", "crates/**/*.rs"]

# Paths to exclude (deny) from the analysis.
deny = ["target/*", "**/testdata/*"]


# --- LLM Provider Configuration ---
[llm]
# The provider to use. Supported: "openai", "anthropic", "deepseek", "null".
# "null" uses a dummy provider for offline/testing mode.
provider = "null"

# For non-null providers, set both `model` and `api_key`.

# API key for the selected provider. Required for non-null providers.
# api_key = "YOUR_API_KEY"

# Optional: override the base URL if using a proxy or self-hosted endpoint.
# base_url = "https://api.openai.com/v1/chat/completions"


# --- Budget Configuration ---
[budget.tokens]
# Maximum tokens available per run (optional).
# max-per-run = 100000


# --- Generation Settings ---
[generation]
# Controls generation behaviour such as temperature.
temperature = 0


# --- Privacy Settings ---
[privacy.redaction]
# Enable redaction of sensitive content from prompts and logs.
enabled = true
# Regular expression patterns to redact.
patterns = []


# --- Rule and Scanner Configuration ---
[rules.secrets]
enabled = true
severity = "medium"

[rules.sql-injection-go]
enabled = true
severity = "medium"

[rules.http-timeouts-go]
enabled = true
severity = "medium"

[rules.convention-deviation]
enabled = true
severity = "medium"

[rules.server-xss-go]
enabled = true
severity = "medium"

